baseURL = 'http://example.org/'
languageCode = 'ja'
title = 'kqns91'
#theme = 'ananke'
#theme = 'cayman-hugo-theme'
#theme = 'hugo-book'
#theme = 'hugo-theme-itheme'
#theme = 'hulga'
#theme = 'mainroad'
#theme = 'toha'
theme = 'pulp'